server:
  port: 8080
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web: DEBUG
spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations: #configuracion de cors
              '[/**]':
                allowedOrigins: "http://localhost:4200" #direccion y puerto del frontend angular
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true
                maxAge: 3600
          routes: #Configuracion de redirecciones a microservicios
            - id: auth-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/auth/**
              filters:
                - StripPrefix=2

            - id: content-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/v1/content/**
              filters:
                - StripPrefix=2

            - id: interaction-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/v1/interaction/**
              filters:
                - StripPrefix=2